$LabConfig=@{ DomainAdminName='CorpAdmin'; AdminPassword='P@ssw0rd'; DomainName='cyber-rangers.lab'; DomainNetbiosName='RANGERS'; DefaultOUName="Lab"; Prefix = 'CYB3RDays2019-'; SwitchName = 'LabSwitch'; DCEdition='4'; Internet=$true ; AdditionalNetworksConfig=@(); VMs=@()}

$LabConfig.VMs += @{ VMName = 'DC2' ; Configuration = 'Simple'; ParentVHD = 'Win2019_G2.vhdx'; MemoryStartupBytes= 2GB ; MGMTNICs=1; AddToolsVHD=$True }
$LabConfig.VMs += @{ VMName = 'DATA' ; Configuration = 'Simple'; ParentVHD = 'Win2019_G2.vhdx'; MemoryStartupBytes= 2GB ; MGMTNICs=1; AddToolsVHD=$True }
$LabConfig.VMs += @{ VMName = 'WEB' ; Configuration = 'Simple'; ParentVHD = 'Win2012R2_G2.vhdx'; MemoryStartupBytes= 2GB ; MGMTNICs=1; AddToolsVHD=$True; Unattend="DjoinCred" }
$LabConfig.VMs += @{ VMName = 'ATA' ; Configuration = 'Simple'; ParentVHD = 'Win2019_G2.vhdx'; MemoryStartupBytes= 2GB ; MGMTNICs=1; AddToolsVHD=$True }
$LabConfig.VMs += @{ VMName = 'CL7' ; Configuration = 'Simple' ; ParentVHD = 'Win7SP1_G1.vhdx'  ; MemoryStartupBytes= 1GB ; MGMTNICs=1; AddToolsVHD=$True ; Generation=1; Unattend="DjoinCred"}
$LabConfig.VMs += @{ VMName = 'CL10A' ; Configuration = 'Simple' ; ParentVHD = 'Win10RS5_G2.vhdx'  ; MemoryStartupBytes= 2GB ; MGMTNICs=1; AddToolsVHD=$True ; DisableWCF=$True ; vTPM=$True; NestedVirt=$true; Wallpaper='blue'}
$LabConfig.VMs += @{ VMName = 'CL10B' ; Configuration = 'Simple' ; ParentVHD = 'Win1019H1_G2.vhdx'  ; MemoryStartupBytes= 2GB ; MGMTNICs=1; AddToolsVHD=$True ; DisableWCF=$True ; vTPM=$True; NestedVirt=$true; Wallpaper='blue'}
$LabConfig.VMs += @{ VMName = 'CL10C' ; Configuration = 'Simple' ; ParentVHD = 'Win1019H1_G2.vhdx'  ; MemoryStartupBytes= 2GB ; MGMTNICs=1; AddToolsVHD=$True ; DisableWCF=$True ; vTPM=$True; NestedVirt=$true; Wallpaper='blue'}
$LabConfig.VMs += @{ VMName = 'CL10D' ; Configuration = 'Simple' ; ParentVHD = 'Win10RS5_G2.vhdx'  ; MemoryStartupBytes= 2GB ; MGMTNICs=1; AddToolsVHD=$True ; DisableWCF=$True ; vTPM=$True; NestedVirt=$true; Wallpaper='blue'}
$LabConfig.VMs += @{ VMName = 'CL10WG' ; Configuration = 'Simple' ; ParentVHD = 'Win10RS5_G2.vhdx'  ; MemoryStartupBytes= 2GB ; MGMTNICs=1; AddToolsVHD=$True ; DisableWCF=$True ; vTPM=$True; NestedVirt=$true; Unattend="NoDjoin"; AdditionalLocalAdmin='LocalAdmin'}